//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarlinDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CartEntities : DbContext
    {
        public CartEntities()
            : base("name=CartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CreditCard> tbl_CreditCard { get; set; }
        public virtual DbSet<tbl_MarlinProduct> tbl_MarlinProduct { get; set; }
        public virtual DbSet<tbl_State> tbl_State { get; set; }
    
        public virtual ObjectResult<GetCreditCardResult> GetCreditCard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCreditCardResult>("GetCreditCard");
        }
    
        public virtual ObjectResult<GetMarlinProductResult> GetMarlinProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMarlinProductResult>("GetMarlinProduct");
        }
    
        public virtual ObjectResult<GetStateDataResult> GetStateData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStateDataResult>("GetStateData");
        }
    }
}
